### PR TITLE
adding my blog entry

### PR DESCRIPTION
**Pull request by SerenaHuang19**
Adding a blog entry.

### CODE REVIEW

**Comment by ttimbers** [comment]
~~yes, that was a misfire, sorry!~~

**Comment by ttimbers** [comment]
My bad @SerenaHuang19 - I read the original email this PR generated and I got it mistaken with an accident I did this morning. Sorry!

**Comment by SerenaHuang19** [comment]
I see, no worries!

**Comment by mgelbart** [comment]
Hi @SerenaHuang19 , I pushed some edits in 0f9a57a280bb4444fb3ac5fd4cc7024b3464495c. Let me know if they look OK to you. My only other comment is whether you want to acknowledge your teammates and/or UBC mentor? Let me know, and then we can merge.

**Comment by SerenaHuang19** [comment]
Sure, that's a good idea - my teammates were Zoe Xu, Chidera Okoma, and Varun Tulasi, and my mentor was Miikka Silfverberg.

**Comment by mgelbart** [comment]
Would you mind adding it in somewhere and then letting me know? Ideally, each name would be a link to some online presence (personal website, linkedin, github, etc) for that person, but if you can't find anything for some of them that's Ok. You're welcome to mention your Unbounce mentors as well, if you'd like.

**Comment by SerenaHuang19** [comment]
Okay, I've made the chances. I couldn't find anything for one of my teammates (Zoe), but I linked to some online presence for everyone else.

**Comment by mgelbart** [comment]
Good to go!

**Pull request merged**
