### PR TITLE
Use the RStudio version of pandoc for Rmarkdown document creation

### PR DESCRIPTION
**Pull request by joelostblom**

### CODE REVIEW

**Comment by joelostblom** [comment]
The path on Linux for the Rstudio pandoc binary is `'/usr/bin/rstudio/bin/quarto/bin/tools'`, could you check on your computers where these are installed on mac (the same?) and windows @flor14 ?

**Comment by flor14** [comment]
Yes

## MacOs
- RStudio
```
> find_pandoc()
$version
[1] ‘2.18’

$dir
[1] "/Applications/RStudio.app/Contents/MacOS/quarto/bin/tools"
```

- Terminal (I deleted it):

```
The following files will be deleted:

/._usr
/usr/._local
/usr/local/._bin
/usr/local/._share
/usr/local/bin/._pandoc
/usr/local/bin/pandoc
/usr/local/share/._man
/usr/local/share/man/._man1
/usr/local/share/man/man1/._pandoc.1
/usr/local/share/man/man1/pandoc.1
```

Then:

```
> library(rmarkdown)
> find_pandoc()
$version
[1] ‘0’

$dir
NULL

```

It continues working on RStudio without problems

**Comment by flor14** [comment]
## Windows 

* RStudio

```
> find_pandoc()
$version
[1] ‘2.18’

$dir
[1] "C:/Program Files/RStudio/bin/quarto/bin/tools"

```
- Terminal

```
> find_pandoc()
$version
[1] '2.19'

$dir
[1] "C:/Users/FLOREN~1/MINICO~1/Library/bin"

```

**Comment by joelostblom** [comment]
Super! Thanks @flor14! I think this is ready to merge, could you double check by running the following on your mac without the separate pandoc installation and see if the marks the PDF and HTML export as OK now?

```
bash <(curl -Ss https://raw.githubusercontent.com/UBC-MDS/UBC-MDS.github.io/rstudio-pandoc-check/resources_pages/check-setup-mds.sh)
```

Note that it should be safe to merge this regardless of whether the paths exist on all systems or not, because worst case scenario is that it falls back onto the pandoc it would detect without the line I added in this PR, so nothing should break.

**Comment by flor14** [comment]
```
# MDS setup check 2022.1

If a program or package is marked as MISSING,
this means that you are missing the required version of that program or package.
Either it is not installed at all or the wrong version is installed.
The required version is indicated with a number and an asterisk (*),
e.g. 4.* means that all versions starting with 4 are accepted (4.0.1, 4.2.5, etc).

You can run the following commands to find out which version
of a program or package is installed (if any):
```
name_of_program --version  # For system programs
conda list  # For Python packages
R -q -e "installed.packages()[,c(Package, Version)]"  # For R packages
```

Checking program and package versions...

## Operating system
ProductName:	macOS
ProductVersion:	12.5
BuildVersion:	21G72

## System programs
OK        psql (PostgreSQL) 14.5
OK        rstudio 2022.07.1+554
OK        R 4.2.1 (2022-06-23) -- "Funny-Looking Kid"
OK        python 3.10.5
OK        conda 4.13.0
OK        bash 3.2.57(1)-release (arm64-apple-darwin21)
OK        git 2.32.1 (Apple Git-133)
OK        make 3.81
OK        latex 3.141592653-2.6-1.40.24 (TeX Live 2022)
OK        tlmgr 58:07 +0200)
OK        docker 20.10.17, build 100c701
OK        code 1.70.1

## Python packages
OK        pandas=1.4.3
OK        pyppeteer=1.0.2
OK        nbconvert=6.4.4
OK        jupyterlab=3.4.5
OK        jupyterlab-git=0.38.0
OK        jupytext=1.14.0
OK        jupyterlab-spellchecker=0.7.2
OK        jupyterlab PDF-generation was successful.
OK        jupyterlab WebPDF-generation was successful.
OK        jupyterlab HTML-generation was successful.

## R packages
OK        tidyverse=1.3.2
OK        markdown=1.1
OK        rmarkdown=2.14
OK        renv=0.15.5
OK        IRkernel=1.3
OK        tinytex=0.40
OK        janitor=2.1.0
OK        gapminder=0.3.0
OK        readxl=1.4.0
OK        ottr=1.1.3
OK        canlang=0.0.1
OK        rmarkdown PDF-generation was successful.
OK        rmarkdown HTML-generation was successful.

The above output has been saved to the file /Users/florenciadandrea/Documents/check-setup-mds.log
together with system configuration details and any detailed error messages about PDF and HTML generation.
You can open this folder in your file browser by typing `open .` (without the surrounding backticks).
```

**Pull request merged**
