### PR TITLE
update quiz and cheatsheet policy

### PR DESCRIPTION
**Pull request by phchen5**

### CODE REVIEW

**Review by zmx721 — APPROVED** [review]
LGTM. Pending updates on cheatsheet upload issue using different browsers.

**Review by ZacWarham — CHANGES_REQUESTED** [review]
We are allowing 50 minutes now not 45 I believe?

Also need to specify if they must do their own work or share cheatsheats

Optionally, what the approval process is (ie if we review after submission or prior)

**Comment by ZacWarham** [comment]
Please also add something along the lines of 

- Cheatsheets must be uploaded using either Chrome or Firefox. Other browsers may not work.

**Review by ZacWarham — APPROVED** [review]
Thanks for the fast turnaround Ben

**Pull request merged**
